CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS plans (
  user_id TEXT PRIMARY KEY REFERENCES users(id),
  plan_json TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
